services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductsDB;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
